CREATE TABLE Stock (
CodigoArticulo INT NOT NULL PRIMARY KEY,
Marca VARCHAR(100) NOT NULL,
Descripcion TEXT NOT NULL,
Precio FLOAT NOT NULL,
Stock INT NOT NULL,
Unidad VARCHAR(100) NOT NULL,
);

CREATE TABLE Cliente (
DNI INT NOT NULL PRIMARY KEY,
Nombre VARCHAR(100) NOT NULL,
Apellido VARCHAR(100) NOT NULL,
);

CREATE TABLE ID_Ventas (
ID_Venta INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
FechaHora DATETIME NOT NULL,
DNI_Cliente INT,
);

CREATE TABLE Ventas (
ID_Venta INT NOT NULL CONSTRAINT FK_Ventas_ID_Ventas FOREIGN KEY REFERENCES ID_Ventas (ID_Venta),
CodigoArticulo INT NOT NULL,
Precio FLOAT NOT NULL,
Cantidad INT NOT NULL,
);

CREATE TABLE ID_Compras (
ID_Compra INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
FechaHora DATETIME NOT NULL,
Proveedor INT,
);

CREATE TABLE Compras (
ID_Compra INT NOT NULL CONSTRAINT FK_Compra_ID_Compra FOREIGN KEY REFERENCES ID_Compras (ID_Compra),
CodigoArticulo INT NOT NULL,
Precio FLOAT NOT NULL,
Cantidad INT NOT NULL,
)


