INSERT INTO products (code, brand, description, price, quentity, unit) VALUES (100101, 'Coca Cola', 'Botella plastico 2,25lts', 350, 20, 'Unidad');
INSERT INTO products (code, brand, description, price, quentity, unit) VALUES (100102, 'Paso de los Toros', 'Botella plastico 2,25lts', 250, 20, 'Unidad');
INSERT INTO products (code, brand, description, price, quentity, unit) VALUES (100103, 'Manaos', 'Botella plastico 2,25lts', 300, 10, 'Unidad');
INSERT INTO products (code, brand, description, price, quentity, unit) VALUES (100104, 'Pepsi', 'Botella plastico 2,25lts', 325, 50, 'Unidad');
INSERT INTO products (code, brand, description, price, quentity, unit) VALUES (100105, '7UP', 'Botella plastico 2,25lts', 170, 3, 'Unidad');
INSERT INTO products (code, brand, description, price, quentity, unit) VALUES (100106, 'Serenisima', 'Manteca 200gr', 100, 9, 'Unidad');
INSERT INTO products (code, brand, description, price, quentity, unit) VALUES (101107, 'Pureza', 'Harina 0000', 450, 20, 'Kilo');
INSERT INTO products (code, brand, description, price, quentity, unit) VALUES (101108, 'Blancaflor', 'Harina 000', 350, 20, 'Kilo');
INSERT INTO products (code, brand, description, price, quentity, unit) VALUES (101109, 'Taragui', 'Yerba de 1kg', 800, 30, 'Kilo');
INSERT INTO products (code, brand, description, price, quentity, unit) VALUES (100110, 'Serenisima', 'Queso Crema cansancrem', 500, 35, 'unit');
INSERT INTO products (code, brand, description, price, quentity, unit) VALUES (101111, '', 'Pan rallado suelto', 350, 20, 'Kilo');
INSERT INTO products (code, brand, description, price, quentity, unit) VALUES (101112, '', 'Harina 0000', 450, 20, 'Kilo');
INSERT INTO products (code, brand, description, price, quentity, unit) VALUES (101113, '', 'Harina 000', 350, 20, 'Kilo');