
//PRDUCTOS
@api_prod = http://localhost:3000/products

### REQUEST PRODUCT
GET {{api_prod}}

### ADD PRODUCT
POST {{api_prod}}
Content-Type: application/json

     {
          "code": 989898,
          "brand": "La Morenita",
          "description": "Cafe de 1kg",
          "price": 2554,
          "quentity": 22,
          "unit": "Pack"
     }


### REQUEST PRODUCT BY CODE
GET {{api_prod}}/100103

### COUNT TOTAL PRODUCT
GET {{api_prod}}/count

### DELETE PRODUCT
DELETE {{api_prod}}/100103

### UPDATE PRODUCT
PUT {{api_prod}}/100103
Content-Type: application/json

{  
     "brand": "Manaos",
     "description": "Botella plastico 1,25lts",
     "price": 100,
     "quentity": 22,
     "unit": "Pack"
}




//CLIENTES
@api_customer = http://localhost:3000/customers

### REQUEST CUSTOMERS
GET {{api_customer}}

### ADD CUSTOMERS
POST {{api_customer}}
Content-Type: application/json

     {
          "dni": 56745677,
          "name": "Daniel",
          "surname": "Varela"
     }

### REQUEST CUSTOMERS BY DNI
GET {{api_customer}}/28564556

### DLETE CUSTOMERS
DELETE {{api_customer}}/29885463

### UPDATE CUSTOMERS
PUT {{api_customer}}/29885463
Content-Type: application/json

     {
          "name": "Facundo",
          "surname": "Vidal"
     }

