@api = http://localhost:3000/products

### Consultar todo la table stock
GET {{api}}

### Agregar un producto a la tabla
POST {{api}}
Content-Type: application/json

     {
          "CodigoArticulo": 888888,
          "Marca": "Repoin",
          "Descripcion": "Cigarrillo bien piola",
          "Precio": 2554.45,
          "Stock": 22,
          "Unidad": "Packa"
     }


### Consultar un producto por el codigo
GET {{api}}/8754687

### Contar total de productos
GET {{api}}/count

### Eliminar un producto por el codigo
DELETE {{api}}/888888

### Actualizar un producto
PUT {{api}}/8754687
Content-Type: application/json

{  
     "Marca": "Melbuour",
     "Descripcion": "Cigarrilo melbuour de 120",
     "Precio": 100,
     "Stock": 22,
     "Unidad": "Pack"
}
